### PR TITLE
Upgrade nan version

### PR DESCRIPTION
**Pull request by kesavkolla**
Bumped the nan version to support node.js 6.x versions.  Closes Issues #39

### CODE REVIEW

**Comment by bishtawi** [comment]
@mcavage Any chance on getting this merged in? Node v6 was released a few months ago and in a couple months it will go LTS.

**Comment by zcstarr** [comment]
@mcavage would be awesome if this got merged in seconded 👍 :)

**Comment by zcstarr** [comment]
\o/

**Comment by xavierchow** [comment]
Any plan to npm publish this fix?

**Comment by chandlerprall** [comment]
@mcavage need to bump this repo's version and publish to npm

**Pull request merged**
