### PR TITLE
Resolve NodeJS v4.x build issue

### PR DESCRIPTION
**Pull request by sempasha**
Resolve issue #27 and #26 (also see nodejs/node#2798)
Thanks to @rvagg for posting [nodejs/nan#376 (comment)](https://github.com/nodejs/nan/issues/376#issuecomment-120838432)

### CODE REVIEW

**Comment by cainvommars** [comment]
@sempasha are u using this in production? I consider branching of and using your code

**Comment by koresar** [comment]
@mcavage Could you please consider merging this?

**Comment by codename-** [comment]
+1

**Comment by sempasha** [comment]
@cainvommars yes, I'm using this in production.

**Comment by koresar** [comment]
@sempasha I forked your repo. Using it in production too. Thank you so much mate!

**Comment by davidporter-id-au** [comment]
+1

**Comment by sempasha** [comment]
@mcavage do not forget to bump package version, due to its incompatible with node v0.x

**Comment by koresar** [comment]
@mcavage yes, please bump the *major* npm version. Otherwise, the things might not go well for many people who did not upgrade to node v4.

**Comment by sempasha** [comment]
As @pfmooney said (see pull request #32), module still works with node v0.10.x. So I was wrong with engine limitation.

**Pull request merged**
